# Generated by Django 4.2.5 on 2023-10-01 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0003_alter_robot_options_robot_unique_model_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="robot",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="robot",
            name="unique_model_version",
        ),
    ]
